### ISSUE TITLE
Broken URLs in documentation

### ISSUE THREAD

**Issue by typesanitizer** [contain-rs/bit-set#13]
For example, on this page:
https://contain-rs.github.io/bit-set/bit_set/struct.Difference.html

Clicking on `[src]` near the top right goes to:
https://contain-rs.github.io/bit-set/src/bit_set/src/lib.rs.html.html#833

whereas the correct address ought to be:
https://contain-rs.github.io/bit-set/src/bit_set/src/lib.rs.html#833

**Comment by pczarn** [comment]
We use docs.rs now
