### ISSUE TITLE
Faster counts on union/intersection/etc

### ISSUE THREAD

**Issue by winstonewert** [contain-rs/bit-set#19]
In my use case, I need to compute:

`a.union(b).count()`

In the current implementation this is really slow. However, if we override the default count implementation for the iterators they could use bitcount to be much more efficient.

Would a PR of that nature be acceptable? Or is the project too "frozen" for that.

**Comment by pczarn** [comment]
I would review and accept a PR for that.

**Comment by winstonewert** [comment]
If you didn't notice, I did put a pull request:

https://github.com/contain-rs/bit-set/pull/20

**Comment by pczarn** [comment]
Rebased in #34
