### ISSUE TITLE
Migrate to `edition = "2021"`

### ISSUE THREAD

**Issue by pczarn** [contain-rs/bit-set#45]

**Comment by waywardmonkeys** [comment]
I was going to do this but noticed that these crates advertise (but don't validate) that they support a very old MSRV.

What should the MSRV policy be fore this and `bit-vec`?

**Comment by pczarn** [comment]
Oh right!! as a compromise I would recommend migrating to `2018` and wait a couple years to bump further to `2021`. Serde requires us (optionally) having 2018 anyway!

I remember some crate having a cool MSRV/SemVer policy, but forgot what it was...

By the way, validation of MSRV is implemented here and you may copy it:  https://github.com/pczarn/gearley/blob/master/.github/workflows/ci.yml#L61-L75

**Comment by pczarn** [comment]
Well, the most important question is: how important is MSRV and how much care should I dedicate to making the policy careful?

**Comment by pczarn** [comment]
@waywardmonkeys Would you still like to do this for set and vec? An expert said Min. Supported Rust Version does not matter that much, because tooling/rustup makes it very easy to update rustc and the entire toolchain.

**Comment by pczarn** [comment]
We should support rustc 1.68.

**Comment by waywardmonkeys** [comment]
I will do it.

**Comment by pczarn** [comment]
Thanks.

**Comment by pczarn** [comment]
Fixed in #53 

@waywardmonkeys I did it
