### ISSUE TITLE
unnecessary use of pointers for remove and contains

### ISSUE THREAD

**Issue by godel9** [contain-rs/bit-set#5]
the remove and contains methods for bitset take an argument of type &usize, but there seems to be no reason for this instead of just taking a usize directly.

**Comment by apasel422** [comment]
The reason is essentially consistency with the other set types (e.g. `BTreeSet`).

**Comment by polazarus** [comment]
Maybe some day there will be a trait for all Set. Until then, I don't think the consistency issue is very relevant.

**Comment by Gankra** [comment]
Arguably they should be taking an `&Q` where `Q: Borrow<usize>` to match the other collections.

**Comment by solson** [comment]
This was somewhat annoying in some cases where I was casting, so the calls looked like:

``` rust
bitset.remove(&(value as usize));
```

I could buy @Gankro's argument, though.

**Comment by Gankra** [comment]
In VecMap we recently merged this change on the reasoning that any future collection trait can be used to paper over this difference. Happy to accept a PR.

**Comment by solson** [comment]
Fix in https://github.com/contain-rs/bit-set/issues/7.
