### ISSUE TITLE
Duplicate license

### ISSUE THREAD

**Issue by tilpner** [contain-rs/bit-set#8]
crates.io indicates MIT/Apache-2.0 for this crate, but the file LICENSE-MIT contains the Apache 2.0 license.

If this is a mistake, I'd be grateful if you could switch the license and republish to crates.io. :)

**Comment by apasel422** [comment]
This looks like a mistake to me. Would you like to submit a PR?

**Comment by tilpner** [comment]
Do you want me to? I assumed that to be unnecessary overhead. Someone has to publish it anyway, might as well switch the license. :/
